// Generated by 'unplugin-auto-import'
export {}
declare global {
  const Checkbox: typeof import('@formily/element-plus/esm')['Checkbox']
  const FormItem: typeof import('@formily/element-plus/esm')['FormItem']
  const createForm: typeof import('@formily/core/esm')['createForm']
  const createSchemaField: typeof import('@formily/vue/esm')['createSchemaField']
}
