// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Form: typeof import('@formily/element-plus/esm')['Form']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Submit: typeof import('@formily/element-plus/esm')['Submit']
  }
}

export {}
